In [1]:
import numpy as np


In [30]:


a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [31]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.86216682 0.5104971 ]
 [0.10891651 0.64185559]]


In [29]:
# Example of simple backpropagation code implemented in numpy
def sigmoid(x, deriv=False):
    return  x*(1-x) if (deriv) else 1/(1+np.exp(-x))

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
np.random.seed(137)


W0 = 2 * np.random.random((3,4)) - 1
W1 = 2 * np.random.random((4,1)) - 1
for i in range(90000):
    l1 = sigmoid(np.dot(X, W0))
    l2 = sigmoid(np.dot(l1, W1))
    l2_delta = (y - l2) * sigmoid(l2, deriv=True)
    l1_delta = l2_delta.dot(W1.T) * sigmoid(l1, deriv=True)
    W1 += l1.T.dot(l2_delta)
    W0 += X.T.dot(l1_delta)

print(f'Training complete - L2 Error: {str(np.mean(np.abs(l2_error)))}')
X_prime = np.array([ [1,1,0],[0,1,0],[1,0,0],[0,0,0],[0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y_prime = sigmoid(np.dot(sigmoid(np.dot(X_prime, W0)), W1))
X_prime, np.rint(y_prime)

Training complete - L2 Error: 0.0041333249264481255


(array([[1, 1, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 1]]),
 array([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.]]))

In [7]:
# Example of CIFAR10 data load
import pickle
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

file_path = './cifar-10-batches-py/data_batch_1'
data_batch_1 = unpickle(file_path)
assert(type(data_batch_1) == dict)
data_batch_1.keys()

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])